version: '3.8'

services:
  # Frontend приложение
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Переменные для сборки
        VITE_BASE_URL: ${VITE_BASE_URL}
    ports:
      - "3000:80"
    environment:
      # Переменные окружения для runtime
      - VITE_BASE_URL=${VITE_BASE_URL}
    volumes:
      # Монтируем .env файл для локальной разработки
      - ./.env:/app/.env:ro
    restart: unless-stopped
    networks:
      - app-network

  # Для разработки - можно раскомментировать
  # frontend-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - VITE_BASE_URL=${VITE_BASE_URL}
  #   command: npm run dev
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

# volumes:
  # Если понадобятся именованные volumes
  # app-data:
