version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_BASE_URL=${VITE_BASE_URL}
    command: npm run dev
    stdin_open: true
    tty: true
