services:
  front:
    image: ${IMAGE_REGISTRY_URL}:dev
    ports:
      - "8088:80"
    environment:
      - VITE_BASE_API_URL=${BASE_API_URL}
    networks:
     - frontend-net
    deploy:
     replicas: 1
     restart_policy:
       condition: on-failure
     placement:
       constraints:
         - node.role == worker

networks:
 frontend-net:
   external:
     true
